import {
  Button,
  Col,
  Container,
  Form,
  ListGroup,
  Modal,
  Row,
} from "react-bootstrap";
import Head from "next/head";

import Layout from "@/components/Layout";
import SessionGuard from "@/components/SessionGuard";
import { useState } from "react";

import { useQuery } from "@apollo/client";

import { GET_PROPERTIES } from "@/client/setup/graphlq/queries";
import CreatePropertyView from "@/components/properties/CreatePropertyView";

export default function Properties() {
  const { data, loading, error } = useQuery(GET_PROPERTIES);

  const [showAddPropertyModal, setShowAddPropertyModal] = useState(false);

  const handleClose = () => {
    setShowAddPropertyModal(false);
  };

  return (
    <>
      <Head>
        <title>Landlord Portal - Properties</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SessionGuard accountType="LANDLORD">
          <Container>
            <Row>
              <Col>
                <h2 style={{ color: "#f2e8cf" }}>
                  Landlord Portal - Properties
                </h2>
                <Button
                  onClick={() => {
                    setShowAddPropertyModal(true);
                  }}
                >
                  New Property
                </Button>
                <ListGroup>
                  {data?.result?.map((p, i) => (
                    <ListGroup.Item key={i}>{p.address.street}</ListGroup.Item>
                  ))}
                </ListGroup>
                <Modal show={showAddPropertyModal} onHide={handleClose}>
                  <Modal.Header closeButton>
                    <Modal.Title>Create Property</Modal.Title>
                  </Modal.Header>
                  <Modal.Body>
                    <CreatePropertyView />
                  </Modal.Body>
                </Modal>
              </Col>
            </Row>
          </Container>
        </SessionGuard>
      </Layout>
    </>
  );
}
