import Head from "next/head";
import Layout from "@/components/Layout";
import { Alert, Container, Row, Col } from "react-bootstrap";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container>
          <Row>
            <Col>
              <Alert variant="primary">Contact</Alert>
            </Col>
          </Row>
        </Container>
      </Layout>
    </>
  );
}
