import { Container, Row, Col, Alert } from "react-bootstrap";
import Head from "next/head";

import Layout from "@/components/Layout";
import Carousel from "@/components/Carousel";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container fluid>
          <Row>
            <Col>
              <Carousel />
            </Col>
          </Row>
        </Container>
        <Container>
          <Row>
            <Col>Container with 1.5rem gutter</Col>
          </Row>
        </Container>
        <Container fluid>
          <Row>
            <Col>Full witdth</Col>
          </Row>
        </Container>
        <Alert variant="primary">Landing Page</Alert>
      </Layout>
    </>
  );
}
