import Head from "next/head";
import Layout from "@/components/Layout";
import { Alert, Col, Container, Row } from "react-bootstrap";

export default function Landlords() {
  return (
    <>
      <Head>
        <title>Landlords</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container className="my-4">
          <Row>
            <Col>
              <Alert variant="primary">Information for Landlords - benefits and stuff</Alert>
            </Col>
          </Row>
        </Container>
      </Layout>
    </>
  );
}
