import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import { Inter } from "@next/font/google";
import { Alert, Button, Col, Container, Row } from "react-bootstrap";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Tenants() {
  return (
    <>
      <Head>
        <title>Tenants</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container>
          <Row>
            <Col>
              <Alert variant="primary">
                Information for Tenants - benefits and stuff
              </Alert>
            </Col>
          </Row>
        </Container>
      </Layout>
    </>
  );
}
