import { Alert, Card, Col, Container, Row } from "react-bootstrap";
import Head from "next/head";

import Layout from "@/components/Layout";
import SessionGuard from "@/components/SessionGuard";

export default function TenantPortal() {
  return (
    <>
      <Head>
        <title>Tenant Portal - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SessionGuard accountType="TENANT">
          <Container>
            <Row>
              <Col>
                <h2 style={{ color: "#f2e8cf" }}>Tenant Portal - Home</h2>
                <Card style={{ width: "18rem", marginTop: "15px" }}>
                  <Card.Body>
                    <Card.Title>My Apartment</Card.Title>
                    <Card.Subtitle className="mb-2 text-muted">
                      1234 N 1st Str 95120 CA
                    </Card.Subtitle>
                    <Card.Text>No new invoices</Card.Text>
                    <Card.Link href="#">Maintenance Request</Card.Link>
                  </Card.Body>
                </Card>
              </Col>
            </Row>
          </Container>
        </SessionGuard>
      </Layout>
    </>
  );
}
