import { Alert } from "react-bootstrap";
import Head from "next/head";

import Layout from "@/components/Layout";
import SessionGuard from "@/components/SessionGuard";

export default function TenantPortal() {
  return (
    <>
      <Head>
        <title>Tenant Portal - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SessionGuard accountType="TENANT">
          <h1>Tenant Portal - Home</h1>
          <Alert variant="primary">
            Landing page for tenant - supposedly active/rented property
          </Alert>
        </SessionGuard>
      </Layout>
    </>
  );
}
