import { useState } from "react";
import {
  Container,
  Row,
  Col,
  Alert,
  Form,
  Button,
  ListGroup,
  ListGroupItem,
} from "react-bootstrap";

import Head from "next/head";

import Layout from "@/components/Layout";
import usMapSvg from "../public/us.svg";
import Image from "next/image";

import PropertySlider from "@/components/properties/PropertySlider";

import { useQuery } from "@apollo/client";
import { GET_PROPERTY } from "@/client/setup/graphlq/queries";
import { useRouter } from "next/router";

import Chance from "chance";
import { Gift, Info, Shield, Smile, Truck } from "react-feather";
import CustomCarousel from "@/components/Carousel";

const chance = new Chance();

export default function Home() {
  const router = useRouter();
  const { id } = router.query;

  const { data, loading, error } = useQuery(GET_PROPERTY, {
    variables: { id },
  });

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Container className="py-3">
          <Row>
            <Col>
              <div className="panel">
                <Row xs={1} sm={2} className="g-3">
                  <Col>
                  <CustomCarousel />
                  </Col>
                  <Col>
                    <h3>
                      ${data?.result?.price}/{data?.result?.rentalTime}
                    </h3>
                    <div className="small">
                      <div className="fw-bold">{data?.result.displayName}</div>
                      <div className="fw-light text-truncate">
                        {data?.result.address.street}
                      </div>
                      <span className="fw-bold">{data?.result?.beds}</span>
                      <span className="fw-light"> bds</span>
                      {" | "}
                      <span className="fw-bold">{data?.result.baths}</span>
                      <span className="fw-light"> ba</span>
                      {" | "}
                      <span className="fw-bold">{data?.result.squareFeet}</span>
                      <span className="fw-light"> sqft</span>
                    </div>
                  </Col>
                </Row>
                <Row xs={2} md={4} className="g-3">
                  <Col style={{ padding: "15px" }}>
                    <Smile style={{ marginRight: "10px" }} />
                    <b>Pet-friendly</b>
                  </Col>
                  <Col style={{ padding: "15px" }}>
                    <Truck style={{ marginRight: "10px" }} />
                    <b>Covered parking</b>
                  </Col>
                  <Col style={{ padding: "15px" }}>
                    <Gift style={{ marginRight: "10px" }} />
                    <b> Mall on-site</b>
                  </Col>
                  <Col style={{ padding: "15px" }}>
                    <Shield style={{ marginRight: "10px" }} />
                    <b>Security</b>
                  </Col>
                </Row>
                <Row xs={1} sm={2} className="g-3">
                  <Col>
                    <h4>Somewhat important information</h4>
                    <p>{chance.paragraph({ sentences: 2 })}</p>
                  </Col>
                  <Col>
                    <h4>Somewhat important information also</h4>
                    <p>{chance.paragraph({ sentences: 2 })}</p>
                  </Col>
                </Row>
                <Row>
                  <Col>
                    <h4>Less important information</h4>
                    <p>{chance.paragraph({ sentences: 10 })}</p>
                    <p>{chance.paragraph({ sentences: 10 })}</p>
                    <p>{chance.paragraph({ sentences: 10 })}</p>
                    <p>{chance.paragraph({ sentences: 10 })}</p>
                  </Col>
                </Row>
                <Row>
                  <Col>
                    <h4>Similar properties</h4>
                    <PropertySlider />
                  </Col>
                </Row>
              </div>
            </Col>
          </Row>
        </Container>
      </Layout>
    </>
  );
}
