import { useState } from "react";
import {
  Container,
  Row,
  Col,
  Alert,
  Form,
  Button,
  ListGroup,
  ListGroupItem,
} from "react-bootstrap";
import Head from "next/head";

import Layout from "@/components/Layout";
import usMapSvg from "../public/us.svg";
import Image from "next/image";

import { useQuery } from "@apollo/client";
import { GET_PROPERTY } from "@/client/setup/graphlq/queries";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const { id } = router.query;

  const { data, loading, error } = useQuery(GET_PROPERTY, {
    variables: { id },
  });

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Container>
          <h2>{data?.result?.displayName}</h2>
        </Container>
      </Layout>
    </>
  );
}
