import { useState } from "react";
import {
  Container,
  Row,
  Col,
  Alert,
  Form,
  Button,
  ListGroup,
  ListGroupItem,
} from "react-bootstrap";

import Head from "next/head";

import Layout from "@/components/Layout";
import usMapSvg from "../public/us.svg";
import Image from "next/image";

import PropertySlider from "@/components/properties/PropertySlider";

import { useQuery } from "@apollo/client";
import { GET_PROPERTY } from "@/client/setup/graphlq/queries";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const { id } = router.query;

  const { data, loading, error } = useQuery(GET_PROPERTY, {
    variables: { id },
  });

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <PropertySlider />
        <Container fluid className="container-full-height property-page">
          <Row>
            <Col>
              <Row
                xs={1}
                md={2}
                className="g-3 py-3"
                style={{ border: "1px solid red" }}
              >
                <Col>
                  <h3>
                    ${data?.result?.price}/{data?.result?.rentalTime}
                  </h3>
                  <div className="small">
                    <div className="fw-bold">{data?.result.displayName}</div>
                    <div className="fw-light text-truncate">
                      {data?.result.address.street}
                    </div>
                    <span className="fw-bold">{data?.result?.beds}</span>
                    <span className="fw-light"> bds</span>
                    {" | "}
                    <span className="fw-bold">{data?.result.baths}</span>
                    <span className="fw-light"> ba</span>
                    {" | "}
                    <span className="fw-bold">{data?.result.squareFeet}</span>
                    <span className="fw-light"> sqft</span>
                  </div>
                </Col>
                <Col style={{ border: "1px solid red" }}>Something else</Col>
              </Row>
            </Col>
            <Col>
              <Row
                xs={1}
                sm={1}
                md={2}
                lg={4}
                className="g-3 py-3"
                style={{ border: "1px solid red" }}
              >
                <Col style={{ border: "1px solid red" }}>
                  1 dfdsfjds iofjd fjods{" "}
                </Col>
                <Col>2 dfsfdoisjoif djiof </Col>
                <Col>3 dfdsofj oidsfj jsdfj odsj</Col>
                <Col>4 ads fdjsofjo jdfdsjof </Col>
              </Row>
              <Row
                xs={1}
                md={2}
                lg={4}
                className="g-3 py-3"
                style={{ border: "1px solid red" }}
              >
                <Col style={{ border: "1px solid red" }}>
                  1 dfdsfjds iofjd fjods{" "}
                </Col>
                <Col>2 dfsfdoisjoif djiof </Col>
                <Col>3 dfdsofj oidsfj jsdfj odsj</Col>
                <Col>4 ads fdjsofjo jdfdsjof </Col>
              </Row>
            </Col>
          </Row>
        </Container>
      </Layout>
    </>
  );
}
